# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dot < Formula
  desc "Universal project companion — scaffold and extend any project from the terminal."
  homepage "https://github.com/version14/dot"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/version14/dot/releases/download/v0.6.0/dot_0.6.0_darwin_amd64.tar.gz"
      sha256 "6f622421f0c21f0b00535a65251f0f2e5c021983bc507b057579a379c53f71de"

      define_method(:install) do
        bin.install "dot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/version14/dot/releases/download/v0.6.0/dot_0.6.0_darwin_arm64.tar.gz"
      sha256 "48bcb5749d8d052d0a82296fcf5effb3990963378eba31fdcd08681c02375603"

      define_method(:install) do
        bin.install "dot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/version14/dot/releases/download/v0.6.0/dot_0.6.0_linux_amd64.tar.gz"
      sha256 "7c14284fa4ee089d1d476c26bf6fd630d3f85ecbd882599cc547c184f8636da1"
      define_method(:install) do
        bin.install "dot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/version14/dot/releases/download/v0.6.0/dot_0.6.0_linux_arm64.tar.gz"
      sha256 "c4f8dfa43506b854821fa3f9373ea38d04d64fdfad7dec43f628bd67b217dbb3"
      define_method(:install) do
        bin.install "dot"
      end
    end
  end

  test do
    system "#{bin}/dot", "version"
  end
end
